//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_repo
    {
        public byte[] download_file { get; set; }
        public long passage_id { get; set; }
        public Nullable<System.DateTime> last_edited { get; set; }
    }
}
