//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passage
    {
        public long passage_id { get; set; }
        public long author_id { get; set; }
        public int is_draft { get; set; }
        public string title { get; set; }
    }
}
